services:
  unihub:
    container_name: unihub
    build: ./
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    ports:
      - "8080:8080"
    networks:
      - unihub
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: unihub-postgres
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql
    ports:
       - "5432:5432"
    networks:
      - unihub
    restart: unless-stopped

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: unless-stopped
    ports:
      - "${VALKEY_PORT_NUMBER}:6379"
    volumes:
      - valkey_data:/data
    command: >
      valkey-server
      --save 60 1
      --loglevel warning
      --appendonly yes
      --requirepass ${VALKEY_PASSWORD}
    env_file:
      - .env
    networks:
      - unihub

volumes:
  db-data:
  valkey_data:

networks:
  unihub:
    driver: bridge
